/**
 * API Title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { LatLng } from "leaflet";
import { ICONS } from "../services/icon.service";
import { Stack } from "./stack";

export interface CardinalDirection {
  north: number;
  east: number;
  south: number;
  west: number;
}

export interface MarkerLatLng {
  latitude: number;
  longitude: number;
  radius: number;
  icon_name: keyof typeof ICONS;
}

export interface NewCard {
  title: string;
  description: string;
  markers: MarkerLatLng[];
  stackId?: number;
}

export interface CardDB {
  id?: number;
  title: string;
  description: string;
  markers: MarkerDB[];
  stack_id?: number;
}

export interface MarkerDB {
  id?: number;
  card_id?: number;
  card?: CardDB;
  longitude: number;
  latitude: number;
  radius: number;
  icon_name: keyof typeof ICONS;
}
