/**
 * API Title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface Coordinate {
  latitude: number;
  longitude: number;
}

export interface NewCard {
  title: string;
  description: string;
  coordinate: Coordinate;
  coordinateRadius?: number;
  category: string;
}

export interface Card {
  id: number;
  name: string;
  description?: string;
  coordinate: Coordinate;
  coordinateRadius?: number;
  categories?: Array<string>;
}

export interface CardDB {
  id: number;
  title: string;
  description: string;
  longitude: number;
  latitude: number;
  coordinate_radius: number;
}
