openapi: '3.0.2'
info:
  title: API Title
  version: '1.0'
servers:
  - url: https://api.server.test/v1
paths:
  /card:
    post:
      description: 'generate new card, if successfull answers with id of the created card'
      requestBody:
        required: true
        description: content of the card to be created
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/card-post-request'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: number
    get:
      description: 'retrieve all card id + name'
      parameters: []
      responses:
        '200':
          description: OK
          content:
              application/json:
                schema:
                  type: array
                  items: 
                    $ref: "#/components/schemas/card"
              
  /card/{cardId}:
    get:
      description: 'get card by id'
      parameters:
        - in: path
          required: true
          name: cardId
          schema:
            type: number
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/card'
components:
  schemas:
    card:
      type: object
      properties:
        id:
          type: number
          example: 1
          pattern: "[0-9]+"
        name:
          type: string
        text:
          type: string
        geo-postion:
          $ref: '#components/schemas/geo-postion'
        postion-radius:
          type: number
        image-url:
          type: string
          format: path
        
        categories:
          type: array
          items:
            type: string
    card-post-request:
      type: object
      properties:
        name:
          type: string
        text:
          type: string
        geo-postion:
          $ref: '#components/schemas/geo-postion'
        postion-radius:
          type: number
        categories:
          type: array
          items:
            type: string
    geo-postion:
      type: object
      properties:
        long:
          type: number
        lat:
          type: number
