name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: install tauri dependencies
      run: sudo apt install libwebkit2gtk-4.1-dev libsoup2.4
    - name: Build
      run: cargo build --verbose
      working-directory: src-tauri
    - name: Run tests
      run: cargo test --verbose
      working-directory: src-tauri

